on: workflow_dispatch
name: Build release app bundle

jobs:
  build:
    name: Build app bundle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17.x'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          #flutter-version: '1.7.8+hotfix.4'
          channel: stable

      - run: flutter pub get
      - name: Decode keystore
        run: echo "$KEYSTORE" | base64 --decode > android/app/keystore.jks
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}

      - name: Build app bundle
        run: flutter build appbundle --flavor ciRelease --release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload app bundle
        uses: actions/upload-artifact@v3
        with:
          name: APK
          path: build/app/outputs/bundle/release/app-release.aab
