on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build Type'
        required: true
        default: 'apk'
        type: choice
        options:
          - apk
          - aab

name: Release

jobs:
  build:
    name: Build APK/AAB
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17.x'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - name: Decode keystore
        run: echo "$KEYSTORE" | base64 --decode > android/app/keystore.jks
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}

      - name: Build APK
        if: ${{ github.event.inputs.buildType == 'apk' }}
        run: flutter build apk --flavor ciRelease --release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Build AAB
        if: ${{ github.event.inputs.buildType == 'aab' }}
        run: flutter build appbundle --flavor ciRelease --release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        if: ${{ github.event.inputs.buildType == 'apk' }}
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: build/app/outputs/flutter-apk/*.apk
          compression-level: 0

      - name: Upload AAB
        if: ${{ github.event.inputs.buildType == 'aab' }}
        uses: actions/upload-artifact@v4
        with:
          name: AAB
          path: build/app/outputs/bundle/ciReleaseRelease/*.aab
          compression-level: 0
