on: push
name: Run flutter tests
jobs:
  test:
    name: Run flutter tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '20.x'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          #flutter-version: '1.7.8+hotfix.4'
          channel: stable
      - run: flutter pub get
      - run: flutter test
